package leetcode;

public class Printer {

    public static void main(String[] args) {
        System.out.println("{\r\n  \"new_cluster\": {\r\n    \"spark_version\": \"8.1.x-scala2.12\",\r\n    \"spark_conf\": {\r\n      \"spark.hadoop.hadoop.security.credential.provider.path\": \"jceks://dbfs@/FileStore/tables/azure_nonprod.jceks\",\r\n      \"spark.executor.extraJavaOptions\": \"-XX:+UseG1GC\",\r\n      \"sink.adls.schema_location\": \"abfss://generic-data-pipeline@forgeinsightsdevstorage.dfs.core.windows.net/engg/communication-table\",\r\n      \"databricks.secret_scope\": \"forgeinsights_akv_scope\",\r\n      \"spark.metrics.workspace.name\": \"hce-forgeinsights-dev-engg-psr-wks\",\r\n      \"spark.databricks.delta.preview.enabled\": \"true\",\r\n      \"spark.driver.extraJavaOptions\": \"-javaagent:/databricks/jars/ranger-spark-plugin-faccess-2.0.0-SNAPSHOT.jar\",\r\n      \"spark.metrics.workspace.orgId\": \"1848683383431148\",\r\n      \"privacera.spark.rowfilter.extention.enable\": \"false\",\r\n      \"privacera.spark.masking.extention.enable\": \"false\"\r\n    },\r\n    \"azure_attributes\": {\r\n      \"availability\": \"ON_DEMAND_AZURE\",\r\n      \"first_on_demand\": 1,\r\n      \"spot_bid_max_price\": -1\r\n    },\r\n    \"node_type_id\": \"Standard_DS3_v2\",\r\n    \"spark_env_vars\": {\r\n      \"PYSPARK_PYTHON\": \"/databricks/python3/bin/python3\"\r\n    },\r\n    \"enable_elastic_disk\": true,\r\n    \"num_workers\": 1,\r\n\t\"init_scripts\": [\r\n\t\t{\r\n\t\t\t\"dbfs\": {\r\n\t\t\t\t\"destination\": \"dbfs:/databricks/spark-monitoring/spark-monitoring.sh\"\r\n\t\t\t}\r\n\t\t}\r\n\t]\r\n  },\r\n  \"libraries\": [\r\n    {\r\n      \"jar\": \"abfss://generic-data-pipeline@forgeinsightsdevstorage.dfs.core.windows.net/engg/app/jars/enrichment/Data-Enricher-uber.jar\"\r\n    },\r\n    {\r\n      \"maven\": {\r\n        \"coordinates\": \"com.azure:azure-identity:1.2.2\"\r\n      }\r\n    },\r\n    {\r\n      \"maven\": {\r\n        \"coordinates\": \"com.azure:azure-security-keyvault-secrets:4.2.4\"\r\n      }\r\n    }\r\n  ],\r\n  \"email_notifications\": {\r\n    \"no_alert_for_skipped_runs\": false\r\n  },\r\n  \"timeout_seconds\": 0,\r\n  \"spark_jar_task\": {\r\n    \"jar_uri\": \"\",\r\n    \"main_class_name\": \"com.forge.insights.data.pipeline.app.DataEnricher\",\r\n    \"parameters\": [\r\n      \"abfss://generic-data-pipeline@forgeinsightsdevstorage.dfs.core.windows.net/engg/config/enricher/JRV-EOM-Schema/af909406-f8c3-4020-b56d-e0014ceaa6d3/JRV-EOM-Schema_af909406-f8c3-4020-b56d-e0014ceaa6d3_enrichment.conf\"\r\n    ],\r\n    \"run_as_repl\": true\r\n  },\r\n  \"max_concurrent_runs\": 1,\r\n  \"name\": \"jrv_af909406-f8c3-4020-b56d-e0014ceaa6d3_enrichment_automatedjob\",\r\n  \"email_notifications\": {}\r\n}\r\n");
    }
}





